# Generated by Django 3.1 on 2020-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200828_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
    ]
