# Generated by Django 3.1 on 2020-08-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200828_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='LastName',
            field=models.CharField(default='LastName', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='firstName', max_length=30),
        ),
    ]
