# Generated by Django 3.1 on 2020-08-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
