# Generated by Django 3.1 on 2020-08-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20200829_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='completed',
        ),
    ]
